/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SupportLazyImport = createFileRoute('/support')()
const SubscriptionLazyImport = createFileRoute('/subscription')()
const ShowsLazyImport = createFileRoute('/shows')()
const MoviesLazyImport = createFileRoute('/movies')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SupportLazyRoute = SupportLazyImport.update({
  path: '/support',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/support.lazy').then((d) => d.Route))

const SubscriptionLazyRoute = SubscriptionLazyImport.update({
  path: '/subscription',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/subscription.lazy').then((d) => d.Route))

<<<<<<< HEAD
const MoviesShowsLazyRoute = MoviesShowsLazyImport.update({
  path: '/movies-shows',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/movies-shows.lazy').then((d) => d.Route))
=======
const ShowsLazyRoute = ShowsLazyImport.update({
  path: '/shows',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/shows.lazy').then((d) => d.Route))

const MoviesLazyRoute = MoviesLazyImport.update({
  path: '/movies',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/movies.lazy').then((d) => d.Route))
>>>>>>> pnpm

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
<<<<<<< HEAD
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/movies-shows': {
      preLoaderRoute: typeof MoviesShowsLazyImport
      parentRoute: typeof rootRoute
    }
    '/subscription': {
=======
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesLazyImport
      parentRoute: typeof rootRoute
    }
    '/shows': {
      id: '/shows'
      path: '/shows'
      fullPath: '/shows'
      preLoaderRoute: typeof ShowsLazyImport
      parentRoute: typeof rootRoute
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
>>>>>>> pnpm
      preLoaderRoute: typeof SubscriptionLazyImport
      parentRoute: typeof rootRoute
    }
    '/support': {
<<<<<<< HEAD
=======
      id: '/support'
      path: '/support'
      fullPath: '/support'
>>>>>>> pnpm
      preLoaderRoute: typeof SupportLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

<<<<<<< HEAD
export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  MoviesShowsLazyRoute,
  SubscriptionLazyRoute,
  SupportLazyRoute,
])
=======
export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  MoviesLazyRoute,
  ShowsLazyRoute,
  SubscriptionLazyRoute,
  SupportLazyRoute,
})
>>>>>>> pnpm

/* prettier-ignore-end */
